name: Detect Duplicate Code (JSCPD)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  jscpd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install jscpd
        run: npm install -g jscpd

      - name: Run jscpd on C++ files
        run: |
          # Scan both src/ and app/ folders recursively
          jscpd "src/**/*.cpp" "app/**/*.cpp" --gitignore --min-lines 3 --min-tokens 25 --threshold 0
